name=ESP32MultiWiFiProvision
version=1.3.1
author=Nainaiu Rakhaine <nainaiu.rakhaine@gmail.com>
maintainer=Nainaiu Rakhaine <nainaiu.rakhaine@gmail.com> (https://www.nainaiurk.me)
sentence=A robust WiFi configuration portal for ESP32 with multi-network storage.
paragraph=Provides a beautiful captive portal, automatic reconnection, connection priority modes (Last Saved, Last Connected, Strongest Signal), blocking and non-blocking APIs, event callbacks, and configurable retries.
category=Communication
url=https://github.com/nainaiurk/ESP32MultiWiFiProvision
architectures=esp32
includes=ESP32MultiWiFiProvision.h
